### ISSUE TITLE
[Bug] Footer not visible

### ISSUE THREAD

**Issue by tryallthethings** [Frazl/chapaachums#2]
The site footer is not visible on my 4K (3840 x 2160) display:
![image](https://github.com/Frazl/chapaachums/assets/11146296/6a8cf3f0-ed93-4daf-a8dc-6ad280e00b09)

On my Full HD (1920x1080) it's partially visible:
![image](https://github.com/Frazl/chapaachums/assets/11146296/5f546c56-7d68-4095-9fab-932b5fc059a7)

**Comment by Frazl** [comment]
Fixed a while ago (I believe)

**Comment by tryallthethings** [comment]
No, this issue is still very much present on 4K (not visible at all) and 1K (partially visible) Resolutions. To clarify: By footer, I was referring to this:
```
<p class="MuiTypography-root MuiTypography-body2 MuiTypography-alignCenter css-rtow1o">Copyright ©  2023 
<a class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-1i1yl23" href="https://github.com/Frazl">Designed By Fraz  </a> . I am no way affiliated with Palia. This is a free website for assisting players. Palia, and any associated logos are trademarks, service marks, and/or registered trademarks of Singularity 6 Corporation.
<a class="MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways css-1i1yl23" href="https://github.com/Frazl/chapaachums">Available on GitHub</a></p>
